-- Table to store topic labels generated by Gemini
-- Partitioned by date for efficient querying of recent labels
-- Clustered by run_id for efficient filtering
CREATE TABLE IF NOT EXISTS `social-listening-sense.social_listening_data.topic_labels` (
    -- Run identification
    run_id STRING NOT NULL,                    -- Unique identifier for this clustering run
    topic_id INT64 NOT NULL,                   -- The topic/cluster ID
    created_at TIMESTAMP NOT NULL,             -- When this label was generated
    
    -- Topic label information
    topic_label STRING NOT NULL,               -- The generated topic label
    topic_description STRING,         -- Optional detailed description of the topic
    confidence_score FLOAT64 NOT NULL,         -- Confidence score from Gemini (if available)
    
    -- Input metadata
    num_documents_used INT64 NOT NULL,         -- Number of documents used to generate the label
    avg_assignment_score FLOAT64 NOT NULL,     -- Average distance to cluster center for used documents
    
    -- Model metadata
    model_metadata JSON,
    
    -- Constraints
    PRIMARY KEY(run_id, topic_id) NOT ENFORCED
)
PARTITION BY DATE(created_at)
CLUSTER BY run_id
OPTIONS(
    description="Stores topic labels generated by Gemini for K-means clusters. Each row represents a labeled topic from a clustering run."
);

-- Add column descriptions
ALTER TABLE `social-listening-sense.social_listening_data.topic_labels`
ALTER COLUMN run_id SET OPTIONS(description="Unique identifier for the clustering run"),
ALTER COLUMN topic_id SET OPTIONS(description="The topic/cluster ID"),
ALTER COLUMN created_at SET OPTIONS(description="Timestamp when the label was generated"),
ALTER COLUMN topic_label SET OPTIONS(description="The generated topic label (max 5 words)"),
ALTER COLUMN topic_description SET OPTIONS(description="Detailed description of the topic (max 2 sentences)"),
ALTER COLUMN confidence_score SET OPTIONS(description="Confidence score from Gemini (0-1)"),
ALTER COLUMN num_documents_used SET OPTIONS(description="Number of documents used to generate the label"),
ALTER COLUMN avg_assignment_score SET OPTIONS(description="Average distance to cluster center for used documents"),
ALTER COLUMN model_metadata SET OPTIONS(description="JSON field containing Gemini model metadata (scores, tokens, version, etc.)"); 