CREATE OR REPLACE TABLE `social-listening-sense.social_listening_data.unified_embeddings_cache` (
    unified_id STRING NOT NULL, -- This MUST be the ID generated by your unified view
    embeddings ARRAY<FLOAT64>,
    embedding_model_name STRING,
    embedding_task_type STRING,
    embedding_generated_at TIMESTAMP
)
OPTIONS(
    description="Stores pre-computed text embeddings for social media posts identified by unified_id from the unified view."
);